### ISSUE TITLE
HTTP fault injection returns 502 (bad gateway) for all requests

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-disruptor#292]
After changes introduced in #271 all HTTP requests forwarded by the agent return a `502 Bad Gateway` error.

**Comment by roobre** [comment]
It seems like this was caused by a dumb typo: `upstreamReq` was cloned and its `RequestURI` cleared, but `req` was passed instead of `upstreamReq` 🤦🏻‍♀️ 

![image](https://github.com/grafana/xk6-disruptor/assets/969721/896ddf1c-38a5-44d6-9cc0-063c91c31b52)


Should be an easy fix, but a better question would be why all tests (including e2e) passed on an scenario where any request could succeed.

**Comment by pablochacin** [comment]
> Unit tests did not catch this mistake because the mocked HTTP client never exercises this request. This is the kind of subtlety that integration tests are good at (re. https://github.com/grafana/xk6-disruptor/issues/183)
> I am not sure why e2e tests did not catch this.

We already have #183 for this discussion about integration tests, but for me, the solution to "e2e test did not catch it" is not to create integration tests because the e2e tests use an actual HTTP server. 

I think the problem is much simpler: we in [the e2e tests](https://github.com/grafana/xk6-disruptor/blob/main/e2e/agent/agent_e2e_test.go#L202-L212) are not checking that we don't introduce errors. We are just checking if we get the error we ask for. 

So, we don't need to add more tests, just one test case to the existing e2e tests. I suggest we do it in the context of fixing this issue.
